package fecal.data;

/**
	Used to configure the names of folders generated by Fecal.
**/
@:structInit
class FolderNames {
	/**
		The name of the folder the executed test content is placed in.
	**/
	public var output: String = "output";

	/**
		The name of the folder containing the content the test results are compared to.
		The output placed in `output` must match the content within `intendedOutput` for
		the test to succeed.
	**/
	public var intendedOutput: String = "intended";

	/**
		If the output of the test is built and executed, this is the name of the folder the
		build is placed.
	**/
	public var build: String = "build";
}
